### ISSUE TITLE
Sequences are reset between each file run when testing with Jest

### ISSUE THREAD

**Issue by Mayeu** [antonversal/typeorm-factory#2]
Hello 👋 

I have been using this module for a bit and it is quite useful, thank you for putting it out there 👍 

We are running our test with Jest, and we have multiple files which are running in parallel (around 7 right now). At first I had no issue with this module because I was only calling each factory from one file. But when I started to call my factory in multiple file, I ended up with relation violation issued by the database.

I am using `.sequence()` in entity field that needs to be unique in the DB, and I generate multiple of those entities, sometimes in multiple file, but when jest run each file, the sequence start from 1 in every file, thus creating DB violation.

Is it the intended behaviour?

**Comment by dan-klasson** [comment]
Yes that's intended behaviour. Use a transactional library to run each test in a transaction like this one: https://github.com/entrostat/typeorm-test-transactions

**Comment by Mayeu** [comment]
@dan-klasson Thank you for your feedback on this :+1:

We can close this then.
